version: '3.2'
services:
  jenkins:
    image: jenkins/jenkins
    environment:
      JENKINS_OPTS: --httpPort=8090
    expose:
      - 8090
    ports:
      - "8090:8090"
      - "50000:50000"
    volumes:
      - type: volume
        source: jenkins_data
        target: /var/jenkins_home
  nexus:
    image: sonatype/nexus3
    expose:
      - 8081
    ports:
      - "8081:8081"
    volumes:
      - type: volume
        source: nexus_data
        target: /nexus-data
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    hostname: 'localhost'
    expose:
      - 443
      - 80
      - 22
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:80'
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - type: volume
        source: gitlab_config
        target: /etc/gitlab
      - type: volume
        source: gitlab_log
        target: /var/log/gitlab
      - type: volume
        source: gitlab_data
        target: /var/opt/gitlab
volumes:
  jenkins_data:
  nexus_data:
  gitlab_config:
  gitlab_log:
  gitlab_data:
